version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: |
          curl -sL https://git.io/goreleaser > goreleaser.sh;
          chmod +x goreleaser.sh;
          ./goreleaser.sh --snapshot --skip-publish;
      - store_artifacts:
          path: dist
  test:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go test -race -v ./...
  release:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  build:
    jobs:
      - build
      - test
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/