version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go test -race -v ./...